panel:
  bind: 127.0.0.1
  port: 7789

export:
  host: "YOUR_PUBLIC_HOST"
  name_prefix: "sbx"

cloudflare_mode: "proxied"   # proxied | direct

users:
  - name: "phone"
    enabled: true
    token: ""
    vless_uuid: ""
    hy2_pass: ""

inbounds:
  reality:
    enabled: true
    listen_port: 443
    server_name: "www.cloudflare.com"
    private_key: ""   # sbxctl reality-keys 生成
    public_key: ""    # 可选
    short_id: ""      # 手动填 1-8 位 hex

  vless_ws_tls:
    enabled: false
    listen_port: 443
    domain: "example.com"
    path: "/ws"
    cert_path: "/etc/ssl/cf/origin.pem"
    key_path:  "/etc/ssl/cf/origin.key"
    acme:
      enabled: false
      provider: "letsencrypt"
      directory_url: ""
      email: "[email protected]"
      domain: ["example.com"]
      data_directory: "/var/lib/sbx/acme"
      disable_http_challenge: true
      disable_tls_alpn_challenge: true
      alternative_http_port: 18080
      alternative_tls_port: 15443
      dns01_challenge:
        provider: "cloudflare"
        api_token: ""

  hysteria2:
    enabled: false
    listen_port: 8443
    up_mbps:
    down_mbps:
    global_password: ""
    tls:
      certificate_path: "/etc/ssl/fullchain.pem"
      key_path: "/etc/ssl/privkey.pem"
      acme:
        enabled: false
        provider: "letsencrypt"
        email: "[email protected]"
        domain: ["hy2.example.com"]
        data_directory: "/var/lib/sbx/acme"
        disable_http_challenge: true
        disable_tls_alpn_challenge: true
        dns01_challenge:
          provider: "cloudflare"
          api_token: ""
